### ISSUE TITLE
Can u do a version for Mi band 6 pls ?

### ISSUE THREAD

**Issue by Smoodie7** [Nadeflore/tetriband#2]
I searched and there is no game in the mi band 6, i think is possible tho, can u try to do a mi band 6 portage ?

**Comment by Nadeflore** [comment]
Unfortunatly It's not possible to make interactive watchfaces or games for the mi band 6. The mi band 6 watchfaces only contains description of how time and other info should be displayed, but it's not possible to write actual code that will be executed on the device.
